"""empty message

Revision ID: cb4cdf3932e7
Revises: 88fa7022258b
Create Date: 2025-01-19 23:30:04.291712

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cb4cdf3932e7'
down_revision: Union[str, None] = '88fa7022258b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrations logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_integrations logs_id'), 'integrations logs', ['id'], unique=False)
    op.create_index(op.f('ix_integrations logs_name'), 'integrations logs', ['name'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_integrations logs_name'), table_name='integrations logs')
    op.drop_index(op.f('ix_integrations logs_id'), table_name='integrations logs')
    op.drop_table('integrations logs')
    # ### end Alembic commands ###
